package com.vaguehope.onosendai.update;

public interface KvKeys {

	String KEY_PREFIX_COL_LAST_REFRESH_TIME = "COL_LAST_REFRESH_TIME_";
	String KEY_PREFIX_COL_LAST_REFRESH_ERROR = "COL_LAST_REFRESH_ERROR_";
	String KEY_PREFIX_COL_LAST_PUSH_TIME = "COL_LAST_PUSH_TIME_";

	String SW_AUTH_TOKEN_PREFIX = "SW_AUTH_TOKEN_";
	String SW_PTA_PREFIX = "SW_PTA_";

	String KEY_HOSAKA_STATUS = "HOSAKA_STATUS";

}
