package com.vaguehope.onosendai;


public interface C {

	String TAG = "onosendai";
	String CONFIG_FILE_NAME = "deck.conf";

	int MAX_MEMORY_IMAGE_CACHE = 20 * 1024 * 1024;
	int DB_CONNECT_TIMEOUT_SECONDS = 5;

	int TWEET_FETCH_PAGE_SIZE = 20;
	int TWITTER_TIMELINE_MAX_FETCH = TWEET_FETCH_PAGE_SIZE * 5;
	int TWITTER_ME_MAX_FETCH = TWEET_FETCH_PAGE_SIZE;
	int TWITTER_MENTIONS_MAX_FETCH = TWEET_FETCH_PAGE_SIZE;
	int TWITTER_LIST_MAX_FETCH = TWEET_FETCH_PAGE_SIZE * 5;

	String DATA_TW_MAX_COL_ENTRIES = "500";

	// Arbitrary values.
	int UPDATER_MIN_COLUMS_TO_USE_THREADPOOL = 2;
	int UPDATER_MAX_THREADS = 3;

	// Form main activity.
	int IMAGE_LOADER_MAX_THREADS = 3;

}
